name: state
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.1
  provider: ^6.0.4
  hydrated_bloc: ^9.0.0
  path_provider: ^2.0.11
  flutter_redux: ^0.10.0
  redux: ^5.0.0
  rxdart: ^0.27.6
  riverpod: ^2.1.1
  flutter_riverpod: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true